<?php
/*
 * Copyright (c) 2018 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */
?>
<table cellspacing="0" id="details-table" class="data-table nested-data-table">
    <col />
    <col width="70" />
    <col width="30" />
    <col width="70" />
    <thead> 
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getItems() as $_item): ?>
        <tr>
            <td>
                <?php echo $this->helper('checkout')->getQuoteItemProductName($_item) ?>
                <?php echo $this->helper('checkout')->getQuoteItemProductDescription($_item) ?>
            </td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()); ?></td>
            <td class="a-center"><?php echo $_item->getQty() ?></td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <?php foreach ($this->getTotals() as $_total): ?>
        <tr>
            <td colspan="3" class="a-right"><?php echo $_total->getTitle() ?></td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($_total->getValue()) ?></td>
        </tr>
    <?php endforeach; ?>
    </tfoot>
</table>
