<?php
/*
 * Copyright (c) 2020 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */
?>
<?php
echo $this->getMethod()->getTitle() . '<br/>';
if ( $this->getInfo()->getLastTransId() == '' ) {
    echo '<em>' . $this->__( 'Redirecting to PayGate...' ) . '</em>';
} else {
    echo $this->__( 'Transaction ID: %s', $this->htmlEscape( $this->getInfo()->getLastTransId() ) ) . '<br/>';
}
